### PR TITLE
Run the LDP test suite

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by cbeer** [comment]
@no-reply : I think this is about as good an integration as I can figure out. Derby is failing a couple MAY/SHOULD tests. Does it make sense to update Derby to support the feature, or figure out how to disable these tests?

**Comment by no-reply** [comment]
Looks pretty good. We should try to refactor this into the tests for RDF::LDP/Lamprey, too.

>  Derby is failing a couple MAY/SHOULD tests. Does it make sense to update Derby to support the feature, or figure out how to disable these tests?

I think the failed shoulds/mays are all deliberate, as documented at https://github.com/ruby-rdf/rdf-ldp/blob/develop/IMPLEMENTATION.md (which could probably use a once over). 

My attitude is that we should let them be unless we have a good reason to change. I think there's value in being lax, to help smoke out unspoken Fedora requirements.

**Comment by cbeer** [comment]
:ok_hand:

**Comment by cbeer** [comment]
@no-reply I've marked the appropriate tests as pending. It looks like we're still failing `testRestrictUriReUseSlug`, although I can't recreate the failure using curl.

**Comment by no-reply** [comment]
@cbeer I opened an issue for that last July: https://github.com/w3c/ldp-testsuite/issues/225

Seems like the best thing is just to mark it pending, too.

**Comment by cbeer** [comment]
:+1:

**Comment by cbeer** [comment]
Looks like some of the LDP test suite is a little flaky.. I'll dig into it.

**Comment by no-reply** [comment]
`NullPointerError` is super informative.

**Comment by cbeer** [comment]
```
java.lang.NullPointerException
    at com.jayway.restassured.internal.support.CloseHTTPClientConnectionInputStreamWrapper.read(CloseHTTPClientConnectionInputStreamWrapper.java:49)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.Reader.read(Reader.java:140)
    at org.apache.jena.atlas.io.CharStreamBuffered$SourceReader.fill(CharStreamBuffered.java:77)
    at org.apache.jena.atlas.io.CharStreamBuffered.fillArray(CharStreamBuffered.java:154)
    at org.apache.jena.atlas.io.CharStreamBuffered.advance(CharStreamBuffered.java:137)
    at org.apache.jena.atlas.io.PeekReader.advanceAndSet(PeekReader.java:241)
    at org.apache.jena.atlas.io.PeekReader.init(PeekReader.java:235)
    at org.apache.jena.atlas.io.PeekReader.peekChar(PeekReader.java:157)
    at org.apache.jena.atlas.io.PeekReader.makeUTF8(PeekReader.java:98)
    at org.apache.jena.riot.tokens.TokenizerFactory.makeTokenizerUTF8(TokenizerFactory.java:41)
    at org.apache.jena.riot.RiotReader.createParser(RiotReader.java:138)
    at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:164)
    at org.apache.jena.riot.RDFDataMgr.process(RDFDataMgr.java:859)
    at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:255)
    at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:241)
    at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:70)
    at com.hp.hpl.jena.rdf.model.impl.ModelCom.read(ModelCom.java:277)
    at org.w3.ldp.testsuite.mapper.RdfObjectMapper.deserialize(RdfObjectMapper.java:44)
    at com.jayway.restassured.mapper.ObjectMapper$deserialize$0.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:218)
    at com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:161)
    at org.w3.ldp.testsuite.test.CommonContainerTest.testDeleteRemovesContainmentTriple(CommonContainerTest.java:740)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
    at org.testng.SuiteRunner.run(SuiteRunner.java:254)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.w3.ldp.testsuite.LdpTestSuite.run(LdpTestSuite.java:375)
    at org.w3.ldp.testsuite.LdpTestSuite.executeTestSuite(LdpTestSuite.java:411)
    at org.w3.ldp.testsuite.LdpTestSuite.executeTestSuite(LdpTestSuite.java:403)
    at org.w3.ldp.testsuite.RunLdpTestSuite.main(RunLdpTestSuite.java:25)
```

**Comment by cbeer** [comment]
@no-reply ok, successfully running against my fork of the test suite.

**Pull request merged**
